spring:
  datasource:
    url: jdbc:postgresql://192.168.1.3:5432/tasktracker_db
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    generate-ddl: true
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: false
      globally_quoted_identifiers: true
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: ssoClient-1
            client-secret: ssoClientSecret-1
            scope: read,write,roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://192.168.1.3:8484/auth/realms/ates/protocol/openid-connect/auth
            token-uri: http://192.168.1.3:8484/auth/realms/ates/protocol/openid-connect/token
            user-info-uri: http://192.168.1.3:8484/auth/realms/ates/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

  thymeleaf:
    cache: false
  cache:
    type: NONE

  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: task_tracker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        schema.registry.url: schema-registry:8081
        auto.register.schemas: true

logging:
  level:
    root: INFO